### ISSUE TITLE
Add the ability to close tabs without changes from VCS

### ISSUE THREAD

**Issue by ggrachdev** [funfried/nb-editor-close-left-right#13]
Good afternoon. I have a great idea for upgrading the plugin. Add the ability to close tabs without changes from VCS. This is sorely lacking in netbeans.

Tabs are closed if:
- there were no file changes
- the file is not new

Many other IDEs have this functionality, but netbeans lags behind. I have to constantly close 30-50 tabs with my hands.

I will be glad if you are interested, thank you!

**Comment by funfried** [comment]
Hi @ggrachdev,

sounds like a great idea, I personally never saw or used such a feature, but I think it could come in handy. I'll check how to implement that feature and add it as soon as I have to time to.

Thanks for the idea.

Cheers,
Fabian

**Comment by funfried** [comment]
@ggrachdev 

I added this feature and another one inspired by this (close tabs from the same/different project).

Please feel free to download the latest SNAPSHOT release and try it yourself! I'll create a release within the next days so it's always available via the official plugin portal.

Thanks again for your great input on this plugin!

Cheers,
Fabian

**Comment by ggrachdev** [comment]
Thank you for your time. We use your plugin as a whole team. It is not possible to assemble a project due to information security restrictions. Have a nice day!

**Comment by funfried** [comment]
Plugin was released (not yet verified from the NetBeans team)

**Comment by ggrachdev** [comment]
Добрый день. Изменения не работают, по крайней мере с Subversion. Есть вкладки не измененные в VSC (черный цвет текста вкладки) и измененные (синий цвет текста вкладки), плагин закрывает все файлы (синие в том числе, хотя они не закомичены). Я правильно понимаю реализованный функционал, что так не должно быть? Спасибо!

**Comment by ggrachdev** [comment]
Good afternoon. The changes don't work, at least with Subversion. There are tabs that have not been changed in VSC (the black color of the tab text) and changed (the blue color of the tab text), the plugin closes all files (including blue ones, although they are not marked). Do I understand the implemented functionality correctly, that it shouldn't be like this? Thanks!
