### ISSUE TITLE
New close actions are not working

### ISSUE THREAD

**Issue by funfried** [funfried/nb-editor-close-left-right#17]
It seems the new project related close actions as well as the VCS related close action are not working correctly. The VCS close action just closes every tab and the project related actions seem to close too many tabs.

**Comment by ggrachdev** [comment]
Good afternoon. The changes don't work, at least with Subversion. There are tabs that have not been changed in VSC (the black color of the tab text) and changed (the blue color of the tab text), the plugin closes all files (including blue ones, although they are not marked). Do I understand the implemented functionality correctly, that it shouldn't be like this? Thanks!

**Comment by funfried** [comment]
Yes, true, I added a bug there and there is already a PR from @XCame but I couldn't merge it yet, I will publish a bug fix release within the next days. Stay tuned.

Cheers,
Fabian

**Comment by funfried** [comment]
Should be fixed in the current SNAPSHOT version and therefore within the up coming release.

**Comment by ggrachdev** [comment]
Checked at work. So far, at least. Thank you!
