### ISSUE TITLE
Netbeans 8.2

### ISSUE THREAD

**Issue by Buzka91** [funfried/nb-editor-close-left-right#2]
Will be there version for new NetBeans?

**Comment by Hanakaze75** [comment]
It would be great indeed ! ^^

**Comment by funfried** [comment]
@Buzka91 and @Hanakaze75 

I just released a new version, I hope it will be available in the plugins of the latest NetBeans IDE versions within the next days. It will support all NetBeans IDE versions starting from 11.0 till the latest (13.0 at the moment).

Cheers,
Fabian
