### ISSUE TITLE
 Add the ability to close [Diff] tabs 

### ISSUE THREAD

**Issue by trixon** [funfried/nb-editor-close-left-right#22]
Hi, and thanks for a really useful plugin.

may one request the possibility to close Diff tabs like the three right most once in the picture?

![bild](https://github.com/funfried/nb-editor-close-left-right/assets/153314/9a261886-1550-4c28-be11-9f946ee32830)

**Comment by funfried** [comment]
Hi @trixon,

thanks, that means a lot to me! I also love your work (mapton)!

I'm looking into it, if I can recognize Diff tabs somehow it should be no problem, maybe I could also close VCS history tabs with that action, it's more or less related. What do you think?

Cheers,
Fabian

**Comment by trixon** [comment]
Nice,
I for one would like them as two separate actions though.
If the menu gets to many items perhaps a sub menu would help? But at the same time, I think it's faster/easier without a sub menu.

**Comment by funfried** [comment]
Hi @trixon,

in the next release this feature will be included as well as an option dialog where the user can disable actions if someone won't use some of the actions and wants to keep the menu smaller.

Cheers,
Fabian

**Comment by trixon** [comment]
Nice!
