### ISSUE TITLE
Cannot install the module because compatibility 

### ISSUE THREAD

**Issue by ramiswailem** [funfried/nb-editor-close-left-right#35]
I got this error:

Activation failed: Cannot enable Close Editor Tabs Left and Right[de.funfried.netbeans.plugins.nb.editor.close.left.right] - module org.netbeans.modules.mercurial > 1.46.1.42.1

`Product Version: Apache NetBeans IDE 22-rc1`
`Java: 21.0.1; OpenJDK 64-Bit Server VM 21.0.1+12-29`
`Runtime: OpenJDK Runtime Environment 21.0.1+12-29`
`System: Mac OS X version 11.7.10 running on x86_64; UTF-8; en_DE (nb)`

**Comment by jkovalsky** [comment]
I face the same issue.

```
Product Version: Apache NetBeans IDE 22-rc1
Java: 21.0.1; Java HotSpot(TM) 64-Bit Server VM 21.0.1+12-LTS-29
Runtime: Java(TM) SE Runtime Environment 21.0.1+12-LTS-29
System: Linux version 5.15.0-105-generic running on amd64; UTF-8; cs_CZ (nb)
```

**Comment by funfried** [comment]
Sorry for the late response, I'm on it, it seems it's not so easy as I break compatibility to older NetBeans versions if I'm just updating to the latest org.netbeans.modules.mercurial version. I'm trying to find a solution to stay compatible with older NetBeans versions as well as supporting the new versions.

**Comment by funfried** [comment]
Fixed within the latest published version (conflicting features were moved into separate extensions for different NetBeans IDE versions)

**Comment by jkovalsky** [comment]
Works fine. Thanks @funfried!
